### PR TITLE
fix: mount remove trailing slash requirement

### LINKED ISSUE #67: Mounts should not require trailing slashes
* When using the mount function a trailing slash is required.
* This makes it impossible to have a mounted route that does not require that a tailing slash be required
* In example below the URL "/product" would result in a 404
* "/product/" would return the expected result

```dart
void main(List<String> args) async {
  load();

  var router = Router();

  router.mount('/auth/', AuthRoutes().router);
  router.mount('/product/', ProductRoutes().router);

  // Final route to return a not found
  router.all('/<.*>', (request) => shelf.Response.notFound(''));

  var handler = const shelf.Pipeline()
    .addMiddleware(shelf.logRequests())
    .addMiddleware(shelf.createMiddleware(requestHandler: AuthManager.handle))
    .addMiddleware(shelf.createMiddleware(requestHandler: ProductController.SecureMiddleware))
    .addHandler(router.handler);

  await io.serve(handler, 'localhost', int.parse(env['PORT'])).then((server) {
    print('Server running on port ${server.port}');
  });

}

class ProductRoutes {

  static FutureOr<Response> middleware(Request request) async {
    print("ProductRoutes Middleware");
    return null;
  }

  Router get router {
    final router = Router();

    var c = ProductController();

    router.get('/', c.GetList);
    router.get('/<product_id>', c.GetById);

    return router;
  }

}
```

### PR DESCRIPTION
**Pull request by felangel**
- closes #67 (related to #140)

### CODE REVIEW

File: shelf_router/test/router_test.dart [hunk 1]
```diff
@@ -148,6 +148,30 @@ void main() {
     expect(await get('/api/hello?ok'), 'middleware');
   });
 
+  test('mount(Router) does not require a trailing slash', () async {
+    var api = Router();
+    api.get('/', (Request request) {
+      return Response.ok('Hello World!');
+    });
```
Comment (jonasfj) [inline shelf_router/test/router_test.dart:155]: Can we make another end-point on `api`, so that we have test that this works for something like `/api/user/jonasfj/info`?

File: shelf_router/test/router_test.dart [hunk 2]
```diff
@@ -148,6 +148,30 @@ void main() {
...
+    app.mount('/api', api);
+
+    app.all('/<_|[^]*>', (Request request) {
+      return Response.ok('catch-all-handler');
+    });
+
+    server.mount(app);
+
+    expect(await get('/hello'), 'hello-world');
+    expect(await get('/api'), 'Hello World!');
```
Comment (jonasfj) [inline shelf_router/test/router_test.dart:171]: Both of these should work, right?
```suggestion
    expect(await get('/api'), 'Hello World!');
    expect(await get('/api/'), 'Hello World!');
```

**Review by jonasfj — CHANGES_REQUESTED** [review]
Looks good, but it would be nice to have a few more tests -- just to be sure (also to guard against regressions in the future).

File: shelf_router/test/router_test.dart (hunk 2 above)
Comment (felangel) [reply shelf_router/test/router_test.dart:175]: yup just added the additional expectation 👍

**Comment by felangel** [comment]
> Looks good, but it would be nice to have a few more tests -- just to be sure (also to guard against regressions in the future).
> 
> Also:
> 
> * [X]  Bump minor version in `pubspec.yaml`,
> * [X]  Update `CHANGELOG.md`
> * [X]  Extend tests to cover `/api`, `/api/`, `/api/user/jonasfj/info`

Sorry for the delay! I updated the test to cover the additional cases you mentioned and update the package version and `CHANGELOG`. Let me know what you think, thanks!

**Comment by felangel** [comment]
@jonasfj any updates on this? Is there anything I can do to push this forward?

**Comment by jonasfj** [comment]
Closed and reopen to retrigger CI.

**Comment by felangel** [comment]
Bump

**Review by jonasfj — APPROVED** [review]
