### PR TITLE
Fixed bug with adding empty map

### LINKED ISSUE #77: yaml_edit issues with empty maps in block style
**Example**
```dart
void main() {
  test('block problems', () {
    final e = YamlEditor('');
    e.update(
      [],
      wrapAsYamlNode(
        {'key': {}},
        collectionStyle: CollectionStyle.BLOCK,
      ),
    );
    return e.toString();
  });
}
```
Causes:
```
  Assertion failed: (package:yaml_edit) Failed to produce valid YAML after modification.

  # YAML before edit:
  > 
  
  # YAML after edit:
  > key:
  > {}
  
  Please file an issue at:
  https://github.com/google/dart-neats/issues/new?labels=pkg%3Ayaml_edit%2C+pending-triage&template=yaml_edit.md
  
  package:yaml_edit/src/editor.dart 585:7   YamlEditor._performEdit
  package:yaml_edit/src/editor.dart 258:14  YamlEditor.update
```
Expected out:

```yaml
key: {}
```
_Block style_ should be used as far as possible.. but it's clearly not possible to use block style for encoding the empty map.

Alternatively, we should do:
```yaml
key:
  {}
```
This would also be acceptable.

/cc @walnutdust

### PR DESCRIPTION
**Pull request by walnutdust**
Resolves #77.

If this PR is accepted, I'm planning on improving the testing and make it a patch release!

/cc @jonasfj

### CODE REVIEW

File: yaml_edit/lib/src/strings.dart [hunk 1]
```diff
@@ -279,7 +279,7 @@ String yamlEncodeBlockString(
       final formattedValue =
           yamlEncodeBlockString(entry.value, newIndentation, lineEnding);
 
-      if (isCollection(entry.value)) {
+      if (isCollection(entry.value) && !isEmpty(entry.value)) {
```
Comment (jonasfj) [inline yaml_edit/lib/src/strings.dart:282]: Can we add a comment that:
`// Empty collections are always encoded in flow-style, so new-line must be avoided`

I assume this is why we have this hack?

**Review by jonasfj — APPROVED** [review]

File: yaml_edit/lib/src/strings.dart (hunk 1 above)
Comment (walnutdust) [reply yaml_edit/lib/src/strings.dart:284]: Yeap! and added!

**Comment by jonasfj** [comment]
@walnutdust we should probably do a `CHANGELOG.md` update too... and port this fix in to `pub` as well.

I'm happy to do a patch release as soon as we have the changelog and version bump in.
